═══════════════════ Testando o código com os casos de teste ═══════════════════
=> Códigos:[runtime.cpp] Testes:[cases.tio(01)] [ϵ]
(ϵ execution)[00] GR:100 cases.tio ()
╭──────────────────────────────────────────────────────────────────────────────
│                    (ϵ execution)[00] GR:100 cases.tio ()                     
├─────────────── INPUT ────────────────┬──────────────── INPUT ────────────────
│ 1                                    │ 1                                   
│ 2                                    │ 2                                   
│ 3                                    │ 3                                   
│ 4                                    │ 4                                   
├───────────── EXPECTED ───────────────┼────────────── RECEIVED ───────────────
│ 1                                    │ terminate called after throwing an i
│ 2                                    │   what():  Overflow                 
│ 3                                    │ fail: runtime exception             
│ 4                                    │                                     
╰──────────────────────────────────────────────────────────────────────────────
