═══════════════════ Testando o código com os casos de teste ═══════════════════
=> Códigos:[exception.cpp] Testes:[cases.tio(01)] [ϵ]
(ϵ execution)[00] GR:100 cases.tio ()
╭──────────────────────────────────────────────────────────────────────────────
│                    (ϵ execution)[00] GR:100 cases.tio ()                     
├─────────────────────────────────── INPUT ────────────────────────────────────
│ 1
│ 2
│ 3
│ 4
├────────────────────────────────── EXPECTED ──────────────────────────────────
│ 1
│ 2
│ 3
│ 4
│ 
├────────────────────────────────── RECEIVED ──────────────────────────────────
│ 1
│ 2
│ terminate called after throwing an instance of 'std::runtime_error'
│   what():  pane no sistema
│ fail: runtime exception
╰──────────────────────────────────────────────────────────────────────────────
