from tko.i18n import Msg


class GuiActionsNames:
    create_draft = Msg.text(pt="Criar Rascunho", en="Create Draft")
    leave = Msg.text(pt="Sair [esc]", en="Quit [esc]")
    edit = Msg.text(pt="Ver tarefa", en="View task")
    show_time = Msg.text(pt="Tempo", en="Time")
    filter = Msg.text(pt="Filtrar", en="Filter")
    principal = Msg.text(pt="Principal", en="Main")
    github = Msg.text(pt="Web", en="Web")
    help = Msg.text(pt="Ajuda", en="Help")
    download = Msg.text(pt="Baixar", en="Download")
    activate = Msg.text(pt="Ativar", en="Activate")
    navigate = Msg.text(pt="←↓→", en="←↓→")
    uncheck = Msg.text(pt="Desmarcar", en="Uncheck")
    search = Msg.text(pt="Busca", en="Search")
    goback = Msg.text(pt="Voltar [Esc]", en="Back [Esc]")
    pallete = Msg.text(pt="Paleta", en="Palette")
    grade = Msg.text(pt="Auto Avaliação", en="Self Evaluation")
    time_limit = Msg.text(pt="Limite de tempo", en="Time limit")
    evaluate_tester = Msg.text(pt="Testar", en="Test")
    execute_tester = Msg.text(pt="Executar", en="Run")
    calibrate = Msg.text(pt="Calibrar teclas", en="Calibrate keys")
    draft = Msg.text(pt="Rascunho", en="Draft")
    all = Msg.text(pt="Todos", en="All")