from tko.i18n import Msg


class GuiActionsNames:
    create_draft = Msg(pt="Criar Rascunho", en="Create Draft")
    leave = Msg(pt="Sair [esc]", en="Quit [esc]")
    edit = Msg(pt="Ver tarefa", en="View task")
    show_time = Msg(pt="Tempo", en="Time")
    filter = Msg(pt="Filtrar", en="Filter")
    principal = Msg(pt="Principal", en="Main")
    github = Msg(pt="Web", en="Web")
    help = Msg(pt="Ajuda", en="Help")
    download = Msg(pt="Baixar", en="Download")
    activate = Msg(pt="Ativar", en="Activate")
    navigate = Msg(pt="←↓→", en="←↓→")
    uncheck = Msg(pt="Desmarcar", en="Uncheck")
    search = Msg(pt="Busca", en="Search")
    goback = Msg(pt="Voltar [Esc]", en="Back [Esc]")
    pallete = Msg(pt="Paleta", en="Palette")
    grade = Msg(pt="Auto Avaliação", en="Self Evaluation")
    time_limit = Msg(pt="Limite de tempo", en="Time limit")
    evaluate_tester = Msg(pt="Testar", en="Test")
    execute_tester = Msg(pt="Executar", en="Run")
    calibrate = Msg(pt="Calibrar teclas", en="Calibrate keys")
    draft = Msg(pt="Rascunho", en="Draft")
    all = Msg(pt="Todos", en="All")