class GuiActions:
    tab = "↔TAB"
    leave   = "Sair"
    edit = "Editar"
    interact  = "Interagir"
    principal = "Principal"
    limite = "Limite"
    github = "Github"
    help = "Ajuda"
    download = "Baixar"
    activate = "Ativar"
    navigate = "←↓→"
    progress = "Quanto"
    uncheck = "Desmarcar"
    search = "Pesquisar"
    self_grade = " Como "
    palette = "Paleta"
    all = "Todos"

class GuiKeys:
    left = "a"
    right = "d"
    down = "s"
    up = "w"

    palette = "p"
    images = "I"
    down_task = "b"
    activate = "\n"
    key_help = "?"
    
    inc_prog1 = "+"
    inc_prog2 = "="
    dec_prog1 = "-"
    dec_prog2 = "_"
    
    inc_self1 = ">"
    inc_self2 = "."
    dec_self1 = "<"
    dec_self2 = ","
    
    set_root_dir = "D"
    set_lang = "L"
    github_open = "g"
    key_quit = "q"
    edit= "e"
    colors = "C"
    borders = "B"
    search = "/"
    graph = "G"
    diff = "m"
    interact = "i"
    test = "\n"
    main = "\t"
    quit   = "q"
    lock = "t"
    limite  = "l"
    expand = "]"
    collapse = "["
    mass = "Y"