class GuiActions:
    tab = "↔TAB"
    leave   = "Sair"
    edit = "Editar"
    filter = "Filtrar"
    principal = "Principal"
    github = "Web   "
    help = "Ajuda"
    download = "Baixar"
    activate = "Ativar"
    navigate = "←↓→"
    uncheck = "Desmarcar"
    search = "Busca"
    pallete = "Paleta"
    grade = "Pontuar"
    # tester frame
    time_limit = "Tempo"
    evaluate_tester = "Avaliar "
    execute_tester  = "Rodar"
    calibrate = "Calibrar"
    all = "Todos"

class GuiKeys:
    calibrate = "C"

    show_graph = "1"
    show_tracks = "2"
    show_quests = "3"
    show_tasks = "4"

    time_view = "T"
    palette = "P"
    images = "I"
    down_task = "b"
    activate = "\n"
    key_help = "?"
    reload_game = "R"
    
    create_draft = "r"
    set_lang_drafts = "L"
    open_url = "u"
    key_quit = "q"
    edit= "e"
    colors = "C"
    borders = "B"
    search = "/"
    grade_play = "p"
    execute_tester = "r" # Interact in manual input
    diff = "d"
    unfold_patch = "V"
    evaluate = "\n"
    toggle_main = "\t"
    quit   = "q"
    lock = "u"
    limite  = "t"
    expand = ">"
    collapse = "<"