╌╌╌╌╌╌╌╌╌Nenhum arquivo de código encontrado. Listando casos de teste.╌╌╌╌╌╌╌╌╌╌
Códigos:[] Testes:[cases.tio(10), cases2.tio(1/3)]
(» não_verificado_)[00] GR:009 cases.tio  (iniciar mostrar e recarregar)
(» não_verificado_)[01] GR:009 cases.tio  (boundary                    )
(» não_verificado_)[02] GR:009 cases.tio  (reset                       )
(» não_verificado_)[03] GR:009 cases.tio  (somando                     )
(» não_verificado_)[04] GR:009 cases.tio  (gastando bateria            )
(» não_verificado_)[05] GR:009 cases.tio  (sem bateria                 )
(» não_verificado_)[06] GR:009 cases.tio  (recarregando                )
(» não_verificado_)[07] GR:009 cases.tio  (dividindo                   )
(» não_verificado_)[08] GR:009 cases.tio  (dividindo por zero          )
(» não_verificado_)[09] GR:009 cases.tio  (gastando bateria            )
(» não_verificado_)[10] GR:009 cases2.tio (novo teste                  )
