═══════════════════ Testando o código com os casos de teste ═══════════════════
=> Códigos:[solver.py] Testes:[cases.tio(07)] [ϵ ω ω ✓ ω ω ✓]
(ϵ erro_execução__)[00] GR:014 cases.tio (duas raízes)
(ω saída_incorreta)[01] GR:014 cases.tio (duas raízes)
(ω saída_incorreta)[02] GR:014 cases.tio (uma raiz   )
(✓ saída_correta__)[03] GR:014 cases.tio (sem raízes )
(ω saída_incorreta)[04] GR:014 cases.tio (05         )
(ω saída_incorreta)[05] GR:014 cases.tio (06         )
(✓ saída_correta__)[06] GR:014 cases.tio (07         )
╭──────────────────────────────────────────────────────────────────────────────
│            (ϵ erro_execução__)[00] GR:014 cases.tio (duas raízes)            
├───────────── INSERIDO ───────────────┬────────────── INSERIDO ───────────────
├───────────── ESPERADO ───────────────┼────────────── RECEBIDO ───────────────
│ 0.44                                 │ Traceback (most recent call last):  
│ -5.07                                │   File "/home/lion/Dropbox/gits/tool
│                                      │     a = float(input())              
│                                      │               ^^^^^^^               
│                                      │ EOFError: EOF when reading a line   
╰──────────────────────────────────────┴───────────────────────────────────────
