═══════════════════ Testando o código com os casos de teste ════════════════════
=> Códigos:[draft.ts] Testes:[cases.tio(10)] [ω ω ω ω ω ω ω ω ω ω]
(ω saída_incorreta)[00] GR:010 cases.tio (inicializar      )
(ω saída_incorreta)[01] GR:010 cases.tio (entrar           )
(ω saída_incorreta)[02] GR:010 cases.tio (limite           )
(ω saída_incorreta)[03] GR:010 cases.tio (sair             )
(ω saída_incorreta)[04] GR:010 cases.tio (limite saida     )
(ω saída_incorreta)[05] GR:010 cases.tio (abastecer        )
(ω saída_incorreta)[06] GR:010 cases.tio (dirigir vazio    )
(ω saída_incorreta)[07] GR:010 cases.tio (dirigir          )
(ω saída_incorreta)[08] GR:010 cases.tio (para longe       )
(ω saída_incorreta)[09] GR:010 cases.tio (enchendo o tanque)
╭──────────────────────────────────────────────────────────────────────────────╮
│         (ω saída_incorreta)[00] GR:010 cases.tio (inicializar      )         │
├────────────────────────────────── INSERIDO ──────────────────────────────────┤
│ show                                                                         │
│ end                                                                          │
├────────────────────────────────── ESPERADO ──────────────────────────────────┤
│ $show                                                                        │
├ pass: 0, gas: 0, km: 0                                                       │
│ $end                                                                         │
├────────────────────────────────── RECEBIDO ──────────────────────────────────┤
│ $show                                                                        │
├ pass: 0, gas: 1, km: 0                                                       │
│ $end                                                                         │
├────────────────────────────────── DESIGUAL ──────────────────────────────────┤
│ pass:·0,·gas:·0,·km:·0↲ (esperado)                                           │
│ pass:·0,·gas:·1,·km:·0↲ (recebido)                                           │
│               ↑         (primeiro)                                           │
╰──────────────────────────────────────────────────────────────────────────────╯
╭──────────────────────────────────────────────────────────────────────────────╮
│         (ω saída_incorreta)[01] GR:010 cases.tio (entrar           )         │
├────────────────────────────────── INSERIDO ──────────────────────────────────┤
│ show                                                                         │
│ enter                                                                        │
│ enter                                                                        │
│ show                                                                         │
│ end                                                                          │
├────────────────────────────────── ESPERADO ──────────────────────────────────┤
│ $show                                                                        │
├ pass: 0, gas: 0, km: 0                                                       │
├ $enter                                                                       │
├ $enter                                                                       │
├ $show                                                                        │
├ pass: 2, gas: 0, km: 0                                                       │
├ $end                                                                         │
├────────────────────────────────── RECEBIDO ──────────────────────────────────┤
│ $show                                                                        │
├ pass: 0, gas: 1, km: 0                                                       │
├ $end                                                                         │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├────────────────────────────────── DESIGUAL ──────────────────────────────────┤
│ pass:·0,·gas:·0,·km:·0↲ (esperado)                                           │
│ pass:·0,·gas:·1,·km:·0↲ (recebido)                                           │
│               ↑         (primeiro)                                           │
╰──────────────────────────────────────────────────────────────────────────────╯
╭──────────────────────────────────────────────────────────────────────────────╮
│         (ω saída_incorreta)[02] GR:010 cases.tio (limite           )         │
├────────────────────────────────── INSERIDO ──────────────────────────────────┤
│ show                                                                         │
│ enter                                                                        │
│ enter                                                                        │
│ show                                                                         │
│ enter                                                                        │
│ show                                                                         │
│ end                                                                          │
├────────────────────────────────── ESPERADO ──────────────────────────────────┤
│ $show                                                                        │
├ pass: 0, gas: 0, km: 0                                                       │
├ $enter                                                                       │
├ $enter                                                                       │
├ $show                                                                        │
├ pass: 2, gas: 0, km: 0                                                       │
├ $enter                                                                       │
├ fail: limite de pessoas atingido                                             │
├ $show                                                                        │
├ pass: 2, gas: 0, km: 0                                                       │
├ $end                                                                         │
├────────────────────────────────── RECEBIDO ──────────────────────────────────┤
│ $show                                                                        │
├ pass: 0, gas: 1, km: 0                                                       │
├ $end                                                                         │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├────────────────────────────────── DESIGUAL ──────────────────────────────────┤
│ pass:·0,·gas:·0,·km:·0↲ (esperado)                                           │
│ pass:·0,·gas:·1,·km:·0↲ (recebido)                                           │
│               ↑         (primeiro)                                           │
╰──────────────────────────────────────────────────────────────────────────────╯
╭──────────────────────────────────────────────────────────────────────────────╮
│         (ω saída_incorreta)[03] GR:010 cases.tio (sair             )         │
├────────────────────────────────── INSERIDO ──────────────────────────────────┤
│ show                                                                         │
│ enter                                                                        │
│ enter                                                                        │
│ show                                                                         │
│ enter                                                                        │
│ show                                                                         │
│ leave                                                                        │
│ show                                                                         │
│ end                                                                          │
├────────────────────────────────── ESPERADO ──────────────────────────────────┤
│ $show                                                                        │
├ pass: 0, gas: 0, km: 0                                                       │
├ $enter                                                                       │
├ $enter                                                                       │
├ $show                                                                        │
├ pass: 2, gas: 0, km: 0                                                       │
├ $enter                                                                       │
├ fail: limite de pessoas atingido                                             │
├ $show                                                                        │
├ pass: 2, gas: 0, km: 0                                                       │
├ $leave                                                                       │
├ $show                                                                        │
├ pass: 1, gas: 0, km: 0                                                       │
├ $end                                                                         │
├────────────────────────────────── RECEBIDO ──────────────────────────────────┤
│ $show                                                                        │
├ pass: 0, gas: 1, km: 0                                                       │
├ $end                                                                         │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├────────────────────────────────── DESIGUAL ──────────────────────────────────┤
│ pass:·0,·gas:·0,·km:·0↲ (esperado)                                           │
│ pass:·0,·gas:·1,·km:·0↲ (recebido)                                           │
│               ↑         (primeiro)                                           │
╰──────────────────────────────────────────────────────────────────────────────╯
╭──────────────────────────────────────────────────────────────────────────────╮
│         (ω saída_incorreta)[04] GR:010 cases.tio (limite saida     )         │
├────────────────────────────────── INSERIDO ──────────────────────────────────┤
│ show                                                                         │
│ enter                                                                        │
│ enter                                                                        │
│ show                                                                         │
│ enter                                                                        │
│ show                                                                         │
│ leave                                                                        │
│ show                                                                         │
│ leave                                                                        │
│ leave                                                                        │
│ show                                                                         │
│ end                                                                          │
├────────────────────────────────── ESPERADO ──────────────────────────────────┤
│ $show                                                                        │
├ pass: 0, gas: 0, km: 0                                                       │
├ $enter                                                                       │
├ $enter                                                                       │
├ $show                                                                        │
├ pass: 2, gas: 0, km: 0                                                       │
├ $enter                                                                       │
├ fail: limite de pessoas atingido                                             │
├ $show                                                                        │
├ pass: 2, gas: 0, km: 0                                                       │
├ $leave                                                                       │
├ $show                                                                        │
├ pass: 1, gas: 0, km: 0                                                       │
├ $leave                                                                       │
├ $leave                                                                       │
├ fail: nao ha ninguem no carro                                                │
├ $show                                                                        │
├ pass: 0, gas: 0, km: 0                                                       │
├ $end                                                                         │
├────────────────────────────────── RECEBIDO ──────────────────────────────────┤
│ $show                                                                        │
├ pass: 0, gas: 1, km: 0                                                       │
├ $end                                                                         │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├────────────────────────────────── DESIGUAL ──────────────────────────────────┤
│ pass:·0,·gas:·0,·km:·0↲ (esperado)                                           │
│ pass:·0,·gas:·1,·km:·0↲ (recebido)                                           │
│               ↑         (primeiro)                                           │
╰──────────────────────────────────────────────────────────────────────────────╯
╭──────────────────────────────────────────────────────────────────────────────╮
│         (ω saída_incorreta)[05] GR:010 cases.tio (abastecer        )         │
├────────────────────────────────── INSERIDO ──────────────────────────────────┤
│ fuel 60                                                                      │
│ show                                                                         │
│ end                                                                          │
├────────────────────────────────── ESPERADO ──────────────────────────────────┤
├ $fuel 60                                                                     │
├ $show                                                                        │
├ pass: 0, gas: 60, km: 0                                                      │
├ $end                                                                         │
├────────────────────────────────── RECEBIDO ──────────────────────────────────┤
├ $show                                                                        │
├ pass: 0, gas: 1, km: 0                                                       │
├ $end                                                                         │
├                                                                              │
├────────────────────────────────── DESIGUAL ──────────────────────────────────┤
│ $fuel·60↲ (esperado)                                                         │
│ $show↲    (recebido)                                                         │
│  ↑        (primeiro)                                                         │
╰──────────────────────────────────────────────────────────────────────────────╯
╭──────────────────────────────────────────────────────────────────────────────╮
│         (ω saída_incorreta)[06] GR:010 cases.tio (dirigir vazio    )         │
├────────────────────────────────── INSERIDO ──────────────────────────────────┤
│ fuel 60                                                                      │
│ show                                                                         │
│ drive 10                                                                     │
│ end                                                                          │
├────────────────────────────────── ESPERADO ──────────────────────────────────┤
├ $fuel 60                                                                     │
├ $show                                                                        │
├ pass: 0, gas: 60, km: 0                                                      │
├ $drive 10                                                                    │
├ fail: nao ha ninguem no carro                                                │
├ $end                                                                         │
├────────────────────────────────── RECEBIDO ──────────────────────────────────┤
├ $show                                                                        │
├ pass: 0, gas: 1, km: 0                                                       │
├ $end                                                                         │
├                                                                              │
├                                                                              │
├                                                                              │
├────────────────────────────────── DESIGUAL ──────────────────────────────────┤
│ $fuel·60↲ (esperado)                                                         │
│ $show↲    (recebido)                                                         │
│  ↑        (primeiro)                                                         │
╰──────────────────────────────────────────────────────────────────────────────╯
╭──────────────────────────────────────────────────────────────────────────────╮
│         (ω saída_incorreta)[07] GR:010 cases.tio (dirigir          )         │
├────────────────────────────────── INSERIDO ──────────────────────────────────┤
│ fuel 60                                                                      │
│ show                                                                         │
│ drive 10                                                                     │
│ enter                                                                        │
│ drive 10                                                                     │
│ show                                                                         │
│ end                                                                          │
├────────────────────────────────── ESPERADO ──────────────────────────────────┤
├ $fuel 60                                                                     │
├ $show                                                                        │
├ pass: 0, gas: 60, km: 0                                                      │
├ $drive 10                                                                    │
├ fail: nao ha ninguem no carro                                                │
├ $enter                                                                       │
├ $drive 10                                                                    │
├ $show                                                                        │
├ pass: 1, gas: 50, km: 10                                                     │
├ $end                                                                         │
├────────────────────────────────── RECEBIDO ──────────────────────────────────┤
├ $show                                                                        │
├ pass: 0, gas: 1, km: 0                                                       │
├ $end                                                                         │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├────────────────────────────────── DESIGUAL ──────────────────────────────────┤
│ $fuel·60↲ (esperado)                                                         │
│ $show↲    (recebido)                                                         │
│  ↑        (primeiro)                                                         │
╰──────────────────────────────────────────────────────────────────────────────╯
╭──────────────────────────────────────────────────────────────────────────────╮
│         (ω saída_incorreta)[08] GR:010 cases.tio (para longe       )         │
├────────────────────────────────── INSERIDO ──────────────────────────────────┤
│ fuel 60                                                                      │
│ show                                                                         │
│ drive 10                                                                     │
│ enter                                                                        │
│ drive 10                                                                     │
│ show                                                                         │
│ drive 70                                                                     │
│ drive 10                                                                     │
│ show                                                                         │
│ end                                                                          │
├────────────────────────────────── ESPERADO ──────────────────────────────────┤
├ $fuel 60                                                                     │
├ $show                                                                        │
├ pass: 0, gas: 60, km: 0                                                      │
├ $drive 10                                                                    │
├ fail: nao ha ninguem no carro                                                │
├ $enter                                                                       │
├ $drive 10                                                                    │
├ $show                                                                        │
├ pass: 1, gas: 50, km: 10                                                     │
├ $drive 70                                                                    │
├ fail: tanque vazio apos andar 50 km                                          │
├ $drive 10                                                                    │
├ fail: tanque vazio                                                           │
├ $show                                                                        │
├ pass: 1, gas: 0, km: 60                                                      │
├ $end                                                                         │
├────────────────────────────────── RECEBIDO ──────────────────────────────────┤
├ $show                                                                        │
├ pass: 0, gas: 1, km: 0                                                       │
├ $end                                                                         │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├────────────────────────────────── DESIGUAL ──────────────────────────────────┤
│ $fuel·60↲ (esperado)                                                         │
│ $show↲    (recebido)                                                         │
│  ↑        (primeiro)                                                         │
╰──────────────────────────────────────────────────────────────────────────────╯
╭──────────────────────────────────────────────────────────────────────────────╮
│         (ω saída_incorreta)[09] GR:010 cases.tio (enchendo o tanque)         │
├────────────────────────────────── INSERIDO ──────────────────────────────────┤
│ fuel 60                                                                      │
│ show                                                                         │
│ drive 10                                                                     │
│ enter                                                                        │
│ drive 10                                                                     │
│ show                                                                         │
│ drive 70                                                                     │
│ drive 10                                                                     │
│ show                                                                         │
│ fuel 200                                                                     │
│ show                                                                         │
│ end                                                                          │
├────────────────────────────────── ESPERADO ──────────────────────────────────┤
├ $fuel 60                                                                     │
├ $show                                                                        │
├ pass: 0, gas: 60, km: 0                                                      │
├ $drive 10                                                                    │
├ fail: nao ha ninguem no carro                                                │
├ $enter                                                                       │
├ $drive 10                                                                    │
├ $show                                                                        │
├ pass: 1, gas: 50, km: 10                                                     │
├ $drive 70                                                                    │
├ fail: tanque vazio apos andar 50 km                                          │
├ $drive 10                                                                    │
├ fail: tanque vazio                                                           │
├ $show                                                                        │
├ pass: 1, gas: 0, km: 60                                                      │
├ $fuel 200                                                                    │
├ $show                                                                        │
├ pass: 1, gas: 100, km: 60                                                    │
├ $end                                                                         │
├────────────────────────────────── RECEBIDO ──────────────────────────────────┤
├ $show                                                                        │
├ pass: 0, gas: 1, km: 0                                                       │
├ $end                                                                         │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├                                                                              │
├────────────────────────────────── DESIGUAL ──────────────────────────────────┤
│ $fuel·60↲ (esperado)                                                         │
│ $show↲    (recebido)                                                         │
│  ↑        (primeiro)                                                         │
╰──────────────────────────────────────────────────────────────────────────────╯
