═══════════════════ Testando o código com os casos de teste ═══════════════════
=> Códigos:[draft.ts] Testes:[cases.tio(10)] [ω ω ω ω ω ω ω ω ω ω]
(ω wrong_out)[00] GR:010 cases.tio (inicializar      )
(ω wrong_out)[01] GR:010 cases.tio (entrar           )
(ω wrong_out)[02] GR:010 cases.tio (limite           )
(ω wrong_out)[03] GR:010 cases.tio (sair             )
(ω wrong_out)[04] GR:010 cases.tio (limite saida     )
(ω wrong_out)[05] GR:010 cases.tio (abastecer        )
(ω wrong_out)[06] GR:010 cases.tio (dirigir vazio    )
(ω wrong_out)[07] GR:010 cases.tio (dirigir          )
(ω wrong_out)[08] GR:010 cases.tio (para longe       )
(ω wrong_out)[09] GR:010 cases.tio (enchendo o tanque)
╭──────────────────────────────────────────────────────────────────────────────
│            (ω wrong_out)[00] GR:010 cases.tio (inicializar      )            
├────────────────────────────────── INSERIDO ──────────────────────────────────
│ show
│ end
├────────────────────────────────── ESPERADO ──────────────────────────────────
│ $show
├ pass: 0, gas: 0, km: 0
│ $end
├────────────────────────────────── RECEBIDO ──────────────────────────────────
│ $show
├ pass: 0, gas: 1, km: 0
│ $end
├────────────────────────────────── DESIGUAL ──────────────────────────────────
│ pass:·0,·gas:·0,·km:·0↲ (esperado)
│ pass:·0,·gas:·1,·km:·0↲ (recebido)
│               ↑         (primeiro)
╰──────────────────────────────────────────────────────────────────────────────
╭──────────────────────────────────────────────────────────────────────────────
│            (ω wrong_out)[01] GR:010 cases.tio (entrar           )            
├────────────────────────────────── INSERIDO ──────────────────────────────────
│ show
│ enter
│ enter
│ show
│ end
├────────────────────────────────── ESPERADO ──────────────────────────────────
│ $show
├ pass: 0, gas: 0, km: 0
├ $enter
├ $enter
├ $show
├ pass: 2, gas: 0, km: 0
├ $end
├────────────────────────────────── RECEBIDO ──────────────────────────────────
│ $show
├ pass: 0, gas: 1, km: 0
├ $end
├ 
├ 
├ 
├ 
├────────────────────────────────── DESIGUAL ──────────────────────────────────
│ pass:·0,·gas:·0,·km:·0↲ (esperado)
│ pass:·0,·gas:·1,·km:·0↲ (recebido)
│               ↑         (primeiro)
╰──────────────────────────────────────────────────────────────────────────────
╭──────────────────────────────────────────────────────────────────────────────
│            (ω wrong_out)[02] GR:010 cases.tio (limite           )            
├────────────────────────────────── INSERIDO ──────────────────────────────────
│ show
│ enter
│ enter
│ show
│ enter
│ show
│ end
├────────────────────────────────── ESPERADO ──────────────────────────────────
│ $show
├ pass: 0, gas: 0, km: 0
├ $enter
├ $enter
├ $show
├ pass: 2, gas: 0, km: 0
├ $enter
├ fail: limite de pessoas atingido
├ $show
├ pass: 2, gas: 0, km: 0
├ $end
├────────────────────────────────── RECEBIDO ──────────────────────────────────
│ $show
├ pass: 0, gas: 1, km: 0
├ $end
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├────────────────────────────────── DESIGUAL ──────────────────────────────────
│ pass:·0,·gas:·0,·km:·0↲ (esperado)
│ pass:·0,·gas:·1,·km:·0↲ (recebido)
│               ↑         (primeiro)
╰──────────────────────────────────────────────────────────────────────────────
╭──────────────────────────────────────────────────────────────────────────────
│            (ω wrong_out)[03] GR:010 cases.tio (sair             )            
├────────────────────────────────── INSERIDO ──────────────────────────────────
│ show
│ enter
│ enter
│ show
│ enter
│ show
│ leave
│ show
│ end
├────────────────────────────────── ESPERADO ──────────────────────────────────
│ $show
├ pass: 0, gas: 0, km: 0
├ $enter
├ $enter
├ $show
├ pass: 2, gas: 0, km: 0
├ $enter
├ fail: limite de pessoas atingido
├ $show
├ pass: 2, gas: 0, km: 0
├ $leave
├ $show
├ pass: 1, gas: 0, km: 0
├ $end
├────────────────────────────────── RECEBIDO ──────────────────────────────────
│ $show
├ pass: 0, gas: 1, km: 0
├ $end
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├────────────────────────────────── DESIGUAL ──────────────────────────────────
│ pass:·0,·gas:·0,·km:·0↲ (esperado)
│ pass:·0,·gas:·1,·km:·0↲ (recebido)
│               ↑         (primeiro)
╰──────────────────────────────────────────────────────────────────────────────
╭──────────────────────────────────────────────────────────────────────────────
│            (ω wrong_out)[04] GR:010 cases.tio (limite saida     )            
├────────────────────────────────── INSERIDO ──────────────────────────────────
│ show
│ enter
│ enter
│ show
│ enter
│ show
│ leave
│ show
│ leave
│ leave
│ show
│ end
├────────────────────────────────── ESPERADO ──────────────────────────────────
│ $show
├ pass: 0, gas: 0, km: 0
├ $enter
├ $enter
├ $show
├ pass: 2, gas: 0, km: 0
├ $enter
├ fail: limite de pessoas atingido
├ $show
├ pass: 2, gas: 0, km: 0
├ $leave
├ $show
├ pass: 1, gas: 0, km: 0
├ $leave
├ $leave
├ fail: nao ha ninguem no carro
├ $show
├ pass: 0, gas: 0, km: 0
├ $end
├────────────────────────────────── RECEBIDO ──────────────────────────────────
│ $show
├ pass: 0, gas: 1, km: 0
├ $end
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├────────────────────────────────── DESIGUAL ──────────────────────────────────
│ pass:·0,·gas:·0,·km:·0↲ (esperado)
│ pass:·0,·gas:·1,·km:·0↲ (recebido)
│               ↑         (primeiro)
╰──────────────────────────────────────────────────────────────────────────────
╭──────────────────────────────────────────────────────────────────────────────
│            (ω wrong_out)[05] GR:010 cases.tio (abastecer        )            
├────────────────────────────────── INSERIDO ──────────────────────────────────
│ fuel 60
│ show
│ end
├────────────────────────────────── ESPERADO ──────────────────────────────────
├ $fuel 60
├ $show
├ pass: 0, gas: 60, km: 0
├ $end
├────────────────────────────────── RECEBIDO ──────────────────────────────────
├ $show
├ pass: 0, gas: 1, km: 0
├ $end
├ 
├────────────────────────────────── DESIGUAL ──────────────────────────────────
│ $fuel·60↲ (esperado)
│ $show↲    (recebido)
│  ↑        (primeiro)
╰──────────────────────────────────────────────────────────────────────────────
╭──────────────────────────────────────────────────────────────────────────────
│            (ω wrong_out)[06] GR:010 cases.tio (dirigir vazio    )            
├────────────────────────────────── INSERIDO ──────────────────────────────────
│ fuel 60
│ show
│ drive 10
│ end
├────────────────────────────────── ESPERADO ──────────────────────────────────
├ $fuel 60
├ $show
├ pass: 0, gas: 60, km: 0
├ $drive 10
├ fail: nao ha ninguem no carro
├ $end
├────────────────────────────────── RECEBIDO ──────────────────────────────────
├ $show
├ pass: 0, gas: 1, km: 0
├ $end
├ 
├ 
├ 
├────────────────────────────────── DESIGUAL ──────────────────────────────────
│ $fuel·60↲ (esperado)
│ $show↲    (recebido)
│  ↑        (primeiro)
╰──────────────────────────────────────────────────────────────────────────────
╭──────────────────────────────────────────────────────────────────────────────
│            (ω wrong_out)[07] GR:010 cases.tio (dirigir          )            
├────────────────────────────────── INSERIDO ──────────────────────────────────
│ fuel 60
│ show
│ drive 10
│ enter
│ drive 10
│ show
│ end
├────────────────────────────────── ESPERADO ──────────────────────────────────
├ $fuel 60
├ $show
├ pass: 0, gas: 60, km: 0
├ $drive 10
├ fail: nao ha ninguem no carro
├ $enter
├ $drive 10
├ $show
├ pass: 1, gas: 50, km: 10
├ $end
├────────────────────────────────── RECEBIDO ──────────────────────────────────
├ $show
├ pass: 0, gas: 1, km: 0
├ $end
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├────────────────────────────────── DESIGUAL ──────────────────────────────────
│ $fuel·60↲ (esperado)
│ $show↲    (recebido)
│  ↑        (primeiro)
╰──────────────────────────────────────────────────────────────────────────────
╭──────────────────────────────────────────────────────────────────────────────
│            (ω wrong_out)[08] GR:010 cases.tio (para longe       )            
├────────────────────────────────── INSERIDO ──────────────────────────────────
│ fuel 60
│ show
│ drive 10
│ enter
│ drive 10
│ show
│ drive 70
│ drive 10
│ show
│ end
├────────────────────────────────── ESPERADO ──────────────────────────────────
├ $fuel 60
├ $show
├ pass: 0, gas: 60, km: 0
├ $drive 10
├ fail: nao ha ninguem no carro
├ $enter
├ $drive 10
├ $show
├ pass: 1, gas: 50, km: 10
├ $drive 70
├ fail: tanque vazio apos andar 50 km
├ $drive 10
├ fail: tanque vazio
├ $show
├ pass: 1, gas: 0, km: 60
├ $end
├────────────────────────────────── RECEBIDO ──────────────────────────────────
├ $show
├ pass: 0, gas: 1, km: 0
├ $end
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├────────────────────────────────── DESIGUAL ──────────────────────────────────
│ $fuel·60↲ (esperado)
│ $show↲    (recebido)
│  ↑        (primeiro)
╰──────────────────────────────────────────────────────────────────────────────
╭──────────────────────────────────────────────────────────────────────────────
│            (ω wrong_out)[09] GR:010 cases.tio (enchendo o tanque)            
├────────────────────────────────── INSERIDO ──────────────────────────────────
│ fuel 60
│ show
│ drive 10
│ enter
│ drive 10
│ show
│ drive 70
│ drive 10
│ show
│ fuel 200
│ show
│ end
├────────────────────────────────── ESPERADO ──────────────────────────────────
├ $fuel 60
├ $show
├ pass: 0, gas: 60, km: 0
├ $drive 10
├ fail: nao ha ninguem no carro
├ $enter
├ $drive 10
├ $show
├ pass: 1, gas: 50, km: 10
├ $drive 70
├ fail: tanque vazio apos andar 50 km
├ $drive 10
├ fail: tanque vazio
├ $show
├ pass: 1, gas: 0, km: 60
├ $fuel 200
├ $show
├ pass: 1, gas: 100, km: 60
├ $end
├────────────────────────────────── RECEBIDO ──────────────────────────────────
├ $show
├ pass: 0, gas: 1, km: 0
├ $end
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├ 
├────────────────────────────────── DESIGUAL ──────────────────────────────────
│ $fuel·60↲ (esperado)
│ $show↲    (recebido)
│  ↑        (primeiro)
╰──────────────────────────────────────────────────────────────────────────────
