════ Testando o código com os casos de teste ═════
=> Códigos:[empty.py] Testes:[_calc.tio(11)] [ω ω ω ω ω ω ω ω ω ω ω]
(ω saída_incorreta)[00] GR:009 _calc.tio (iniciar mostrar e recarregar       )
(ω saída_incorreta)[01] GR:009 _calc.tio (charge                             )
(ω saída_incorreta)[02] GR:009 _calc.tio (boundary                           )
(ω saída_incorreta)[03] GR:009 _calc.tio (reset                              )
(ω saída_incorreta)[04] GR:009 _calc.tio (somando                            )
(ω saída_incorreta)[05] GR:009 _calc.tio (gastando bateria                   )
(ω saída_incorreta)[06] GR:009 _calc.tio (sem bateria                        )
(ω saída_incorreta)[07] GR:009 _calc.tio (recarregando                       )
(ω saída_incorreta)[08] GR:009 _calc.tio (dividindo                          )
(ω saída_incorreta)[09] GR:009 _calc.tio (dividindo por zero gastando bateria)
(ω saída_incorreta)[10] GR:009 _calc.tio (gastando bateria                   )
╭────────────────────────────────────────────────╮
│(ω saída_incorreta)[00] GR:009 _calc.tio (inicia│
├────── INSERIDO ───────┬────── INSERIDO ────────┤
│ init 5                │ init 5                 │
│ show                  │ show                   │
│ end                   │ end                    │
├────── ESPERADO ───────┼────── RECEBIDO ────────┤
├ $init 5               ├                        │
├ $show                 ├                        │
├ display = 0.00, batte ├                        │
├ $end                  ├                        │
├─────────────────── DESIGUAL ───────────────────┤
│ $init·5↲ (esperado)                            │
│ ↲        (recebido)                            │
│ ↑        (primeiro)                            │
╰────────────────────────────────────────────────╯
